services:
  weaviate:
    image: semitechnologies/weaviate:1.19.6
    ports:
      - "9081:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    volumes:
      - weaviate_data:/var/lib/weaviate
    deploy:
      resources:
        limits:
          memory: ${WEAVIATE_MEMORY_LIMIT:-2G}
          cpus: ${WEAVIATE_CPU_LIMIT:-1}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5.9.0
    ports:
      - "9475:7474"
      - "9687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_pagecache_size: ${NEO4J_MEMORY_PAGECACHE:-512M}
      NEO4J_dbms_memory_heap_initial__size: ${NEO4J_MEMORY_HEAP_INITIAL:-512M}
      NEO4J_dbms_memory_heap_max__size: ${NEO4J_MEMORY_HEAP_MAX:-1G}
    volumes:
      - neo4j_data:/data
    deploy:
      resources:
        limits:
          memory: ${NEO4J_MEMORY_LIMIT:-2G}
          cpus: ${NEO4J_CPU_LIMIT:-1}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    ports:
      - "29017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    command: ["--auth", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    deploy:
      resources:
        limits:
          memory: ${MONGODB_MEMORY_LIMIT:-1G}
          cpus: ${MONGODB_CPU_LIMIT:-1}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.3
    ports:
      - "9001:8000"
    environment:
      CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER: token
      CHROMA_SERVER_AUTH_CREDENTIALS: ${ROO_CHROMA_AUTH_TOKEN:-admin_token}
      CHROMA_SERVER_AUTH_PROVIDER: token
      ALLOW_RESET: 'true'
      CHROMA_OTEL_EXPORTER_ENDPOINT: ''
      CHROMA_OTEL_SERVICE_NAME: 'chroma'
      CHROMA_OTEL_COLLECTION_ENDPOINT: ''
      NUMPY_EXPERIMENTAL_ARRAY_FUNCTION: '1'
    volumes:
      - chroma_data:/chroma/chroma
    deploy:
      resources:
        limits:
          memory: ${CHROMA_MEMORY_LIMIT:-1G}
          cpus: ${CHROMA_CPU_LIMIT:-1}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  weaviate_data:
  neo4j_data:
  mongodb_data:
  mongodb_config:
  chroma_data: